### ISSUE TITLE
Documentation - how to get started?

### ISSUE THREAD

**Issue by fabarea** [TYPO3-Surf-CMS/Surf.CMS#10]
Hi,

Could you add a few lines in the README how to get started? 

After cloning I did `composer install`. Then `./flow surf:list` which still returns an empty list of tasks.

I created a new `Build/BuildEssentials/Surf/Surf.php` and added the sample code in the README. However command `./flow surf:list` remains an empty list. What is missing?

**Comment by fabarea** [comment]
Yes, but where should the Surf file be located? Still new to Surf... I put the example snippet as such in file `Build/BuildEssentials/Surf/Surf.php` but `./flow surf:list` remains empty. Normal?

**Comment by helhum** [comment]
I committed the example file to the location it belongs. As you can see in 9d67df6a661263f24addbb259ccc999a0ab9405d, it must be in `Build/Surf` not `Build/BuildEssentials/Surf`

**Comment by fabarea** [comment]
Of course! I overlooked it. Thanks for helping, much appreciated.

**Comment by vendytjung** [comment]
I got error: Got exception "Extension "coreapi" is not found! Make sure it is available in your project, or remove this task in your deployment configuration!" rolling back.

how can i remove the task?

**Comment by helhum** [comment]
```
$deployment->onInitialize(function() use ($workflow, $application) {
    $workflow->removeTask('typo3.surf.cms:typo3:cms:compareDatabase');
    $workflow->removeTask('typo3.surf.cms:typo3:cms:flushCaches');
});
```

**Comment by vendytjung** [comment]
Thanks. It works :)
can you recommend any documentation? I'm still getting Error, if i try use "Web" in browser.
#1318414040: The SubRoute Package "TYPO3.Welcome" referenced in Route "Welcome" is not available.

**Comment by helhum** [comment]
> The SubRoute Package "TYPO3.Welcome"

Maybe you ask in the Neos guys... http://slack.neos.io/
